#Regresión Lineal con Python
##El paquete `scikit-learn` para la regresión lineal y selección de rasgos.

In [1]:
# RFE = Recursive Feature Elimination (Eliminación de funciones recursivas)
# SVR = Support Vector Regression (Soporte Vectorial de Regresión)

from sklearn.feature_selection import RFE
from sklearn.svm import SVR
import numpy as np
import pandas as pd

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [3]:
data = pd.read_csv("/content/drive/MyDrive/Machine Learning - Python/Datasets - Machine Learning/ads/Advertising.csv")

In [4]:
data.head()

,TV,Radio,Newspaper,Sales
0,230.1,37.8,69.2,22.1
1,44.5,39.3,45.1,10.4
2,17.2,45.9,69.3,9.3
3,151.5,41.3,58.5,18.5
4,180.8,10.8,58.4,12.9


In [5]:
feature_cols = ["TV", "Radio", "Newspaper"]

In [6]:
X = data[feature_cols]
Y = data["Sales"]

In [7]:
estimator = SVR(kernel = "linear")
selector_0 = RFE(estimator, n_features_to_select = 2, step = 1)
selector = selector_0.fit(X, Y)

In [8]:
selector.support_

array([ True,  True, False])

In [9]:
selector.ranking_

array([1, 1, 2])

In [10]:
from sklearn.linear_model import LinearRegression

In [11]:
X_pred = X[["TV", "Radio"]]

In [12]:
lm = LinearRegression()

In [16]:
lm.fit(X_pred, Y)

LinearRegression()

In [14]:
lm.intercept_

2.9210999124051362

In [15]:
lm.coef_

array([0.04575482, 0.18799423])

In [17]:
# Para calcular el r^2 ajustado:
lm.score(X_pred, Y)

0.8971942610828957