# El Método de K-Means

In [ ]:
import numpy as np

In [ ]:
data = np.random.random(90).reshape(30, 3)
data

array([[0.57113373, 0.08493786, 0.97489688],
       [0.16713099, 0.0514821 , 0.34620206],
       [0.84567997, 0.82478229, 0.71322657],
       [0.59204461, 0.0386171 , 0.42303071],
       [0.34367939, 0.59822644, 0.92357738],
       [0.32201714, 0.63722053, 0.37103049],
       [0.24082072, 0.66429606, 0.24685429],
       [0.07577432, 0.924124  , 0.40731005],
       [0.3821555 , 0.97396829, 0.00218387],
       [0.4859924 , 0.16767526, 0.34070665],
       [0.16602257, 0.06387187, 0.86077736],
       [0.7915238 , 0.20199202, 0.74741395],
       [0.16301138, 0.15258002, 0.65603834],
       [0.28243235, 0.82661399, 0.5271491 ],
       [0.56232911, 0.10566921, 0.49194924],
       [0.40248906, 0.73709188, 0.14923175],
       [0.16867236, 0.42492398, 0.34332415],
       [0.02278279, 0.42794379, 0.65895465],
       [0.4002783 , 0.00926545, 0.46297724],
       [0.2078459 , 0.83824318, 0.96485232],
       [0.9477764 , 0.09052379, 0.86504616],
       [0.76629479, 0.43852732, 0.28113784],
       [0.

In [ ]:
data[0]

array([0.57113373, 0.08493786, 0.97489688])

In [ ]:
c1 = np.random.choice(range(len(data)))
c2 = np.random.choice(range(len(data)))

In [ ]:
c1, c2

(9, 13)

In [ ]:
clust_centers = np.vstack([data[c1], data[c2]])

In [ ]:
clust_centers

array([[0.4859924 , 0.16767526, 0.34070665],
       [0.28243235, 0.82661399, 0.5271491 ]])