## Análisis de Componentes Principales - Paso a paso

* Estandarizar los datos (para cada una de las m observaciones).
* Obtener los valores propios y vectores propios a partir de la matriz de covarianzas, o de correlaciones, o de incluso de la SVD.
* Ordenar los valores propios en orden descendente y quedarnos con los p que se correspondan a los p mayores y así disminuir el número de variables del dataset (p menor que m).
* Construir la matriz de proyección W a partir de los vectores propios.
* Transformar el dataset original X a través de W para así obtener datos en el subespacio Y de dimensión p.

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('/content/drive/MyDrive/Machine Learning - Python/Datasets - Machine Learning/iris/iris.csv')

In [4]:
df.head()

,Sepal.Length,Sepal.Width,Petal.Length,Petal.Width,Species
0,5.1,3.5,1.4,0.2,setosa
1,4.9,3.0,1.4,0.2,setosa
2,4.7,3.2,1.3,0.2,setosa
3,4.6,3.1,1.5,0.2,setosa
4,5.0,3.6,1.4,0.2,setosa


In [5]:
df.iloc[:,0:4].values

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [6]:
df.iloc[:,4].values

array(['setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolo

In [7]:
X = df.iloc[:,0:4].values
y = df.iloc[:,4].values

In [8]:
!pip install plotly
import plotly.io as pio
import plotly.graph_objects as go
from plotly.graph_objs import Data, Layout, Histogram, Marker, XAxis, YAxis

In [9]:
traces = []
legend = {0:True, 1:True, 2:True, 3:True}

In [10]:
colors = {'setosa': 'rgb(255, 127, 20)',
          'versicolor': 'rgb(31, 220, 120)',
          'virginica': 'rgb(44, 50, 180)'
          }

In [11]:
for col in range(4):
    for key in colors:
        traces.append(Histogram(x = X[y == key, col],
                                opacity = 0.7,
                                xaxis = 'x%s'%(col + 1),
                                marker = Marker(color = colors[key]),
                                name = key,
                                showlegend = legend[col]))
    legend = {0:False, 1:False, 2:False, 3:False}

/usr/local/lib/python3.10/dist-packages/plotly/graph_objs/_deprecations.py:434: DeprecationWarning: plotly.graph_objs.Marker is deprecated.
Please replace it with one of the following more specific types
  - plotly.graph_objs.scatter.Marker
  - plotly.graph_objs.histogram.selected.Marker
  - etc.

  warnings.warn(


In [12]:
data = Data(traces)
layout = Layout(barmode = 'overlay',
                xaxis = XAxis(domain = [0, 0.25], title = 'Long. Sépalos (cm)'),
                xaxis2 = XAxis(domain = [0.3, 0.5], title = 'Anch. Sépalos (cm)'),
                xaxis3 = XAxis(domain = [0.55, 0.75], title = 'Long. Pétalos (cm)'),
                xaxis4 = XAxis(domain = [0.8, 1.0], title = 'Anch. Pétalos (cm)'),
                yaxis = YAxis(title = 'Número de ejemplares'),
                title = 'Distribución de los rasgos de las diferentes flores Iris')

/usr/local/lib/python3.10/dist-packages/plotly/graph_objs/_deprecations.py:31: DeprecationWarning: plotly.graph_objs.Data is deprecated.
Please replace it with a list or tuple of instances of the following types
  - plotly.graph_objs.Scatter
  - plotly.graph_objs.Bar
  - plotly.graph_objs.Area
  - plotly.graph_objs.Histogram
  - etc.

  warnings.warn(
/usr/local/lib/python3.10/dist-packages/plotly/graph_objs/_deprecations.py:544: DeprecationWarning: plotly.graph_objs.XAxis is deprecated.
Please replace it with one of the following more specific types
  - plotly.graph_objs.layout.XAxis
  - plotly.graph_objs.layout.scene.XAxis

  warnings.warn(
/usr/local/lib/python3.10/dist-packages/plotly/graph_objs/_deprecations.py:572: DeprecationWarning: plotly.graph_objs.YAxis is deprecated.
Please replace it with one of the following more specific types
  - plotly.graph_objs.layout.YAxis
  - plotly.graph_objs.layout.scene.YAxis

  warnings.warn(


In [13]:
fig = go.Figure(data=data, layout=layout)
fig.show() # if you're using newer versions of plotly

In [14]:
from sklearn.preprocessing import StandardScaler

In [15]:
X_std = StandardScaler().fit_transform(X)

In [16]:
for col in range(4):
    for key in colors:
        traces.append(Histogram(x = X_std[y == key, col],
                                opacity = 0.7,
                                xaxis = 'x%s'%(col + 1),
                                marker = Marker(color = colors[key]),
                                name = key,
                                showlegend = legend[col]))
    legend = {0:False, 1:False, 2:False, 3:False}

/usr/local/lib/python3.10/dist-packages/plotly/graph_objs/_deprecations.py:434: DeprecationWarning:

plotly.graph_objs.Marker is deprecated.
Please replace it with one of the following more specific types
  - plotly.graph_objs.scatter.Marker
  - plotly.graph_objs.histogram.selected.Marker
  - etc.




In [17]:
data = Data(traces)
layout = Layout(barmode = 'overlay',
                xaxis = XAxis(domain = [0, 0.25], title = 'Long. Sépalos (cm)'),
                xaxis2 = XAxis(domain = [0.3, 0.5], title = 'Anch. Sépalos (cm)'),
                xaxis3 = XAxis(domain = [0.55, 0.75], title = 'Long. Pétalos (cm)'),
                xaxis4 = XAxis(domain = [0.8, 1.0], title = 'Anch. Pétalos (cm)'),
                yaxis = YAxis(title = 'Número de ejemplares'),
                title = 'Distribución de los rasgos de las diferentes flores Iris')

/usr/local/lib/python3.10/dist-packages/plotly/graph_objs/_deprecations.py:31: DeprecationWarning:

plotly.graph_objs.Data is deprecated.
Please replace it with a list or tuple of instances of the following types
  - plotly.graph_objs.Scatter
  - plotly.graph_objs.Bar
  - plotly.graph_objs.Area
  - plotly.graph_objs.Histogram
  - etc.


/usr/local/lib/python3.10/dist-packages/plotly/graph_objs/_deprecations.py:544: DeprecationWarning:

plotly.graph_objs.XAxis is deprecated.
Please replace it with one of the following more specific types
  - plotly.graph_objs.layout.XAxis
  - plotly.graph_objs.layout.scene.XAxis


/usr/local/lib/python3.10/dist-packages/plotly/graph_objs/_deprecations.py:572: DeprecationWarning:

plotly.graph_objs.YAxis is deprecated.
Please replace it with one of the following more specific types
  - plotly.graph_objs.layout.YAxis
  - plotly.graph_objs.layout.scene.YAxis




In [18]:
fig = go.Figure(data=data, layout=layout)
fig.show() # if you're using newer versions of plotly

##1. Realizamos el cálculo de los valores y vectores propios.

####a) Usando la matriz de covarianzas.

In [19]:
import numpy as np

In [20]:
mean_vect = np.mean(X_std, axis = 0)
mean_vect

array([-4.73695157e-16, -7.81597009e-16, -4.26325641e-16, -4.73695157e-16])

In [21]:
cov_matrix = (X_std - mean_vect).T.dot((X_std - mean_vect)) / (X_std.shape[0] - 1)
cov_matrix

array([[ 1.00671141, -0.11835884,  0.87760447,  0.82343066],
       [-0.11835884,  1.00671141, -0.43131554, -0.36858315],
       [ 0.87760447, -0.43131554,  1.00671141,  0.96932762],
       [ 0.82343066, -0.36858315,  0.96932762,  1.00671141]])

In [22]:
np.cov(X_std.T)

array([[ 1.00671141, -0.11835884,  0.87760447,  0.82343066],
       [-0.11835884,  1.00671141, -0.43131554, -0.36858315],
       [ 0.87760447, -0.43131554,  1.00671141,  0.96932762],
       [ 0.82343066, -0.36858315,  0.96932762,  1.00671141]])

In [23]:
eig_vals, eig_vectors = np.linalg.eig(cov_matrix)

In [24]:
print('Valores propios:')
eig_vals

Valores propios:


array([2.93808505, 0.9201649 , 0.14774182, 0.02085386])

In [25]:
print('Vectores propios:')
eig_vectors

Vectores propios:


array([[ 0.52106591, -0.37741762, -0.71956635,  0.26128628],
       [-0.26934744, -0.92329566,  0.24438178, -0.12350962],
       [ 0.5804131 , -0.02449161,  0.14212637, -0.80144925],
       [ 0.56485654, -0.06694199,  0.63427274,  0.52359713]])

###b) Usando la matriz de correlaciones.

In [26]:
corr_matrix = np.corrcoef(X_std.T)
corr_matrix

array([[ 1.        , -0.11756978,  0.87175378,  0.81794113],
       [-0.11756978,  1.        , -0.4284401 , -0.36612593],
       [ 0.87175378, -0.4284401 ,  1.        ,  0.96286543],
       [ 0.81794113, -0.36612593,  0.96286543,  1.        ]])

In [27]:
'''
Notemos que el resltado siguiente es igual al anterior.
No hay necesidad de usar X_std, sino sólo X.
'''

corr_matrix = np.corrcoef(X.T)
corr_matrix

array([[ 1.        , -0.11756978,  0.87175378,  0.81794113],
       [-0.11756978,  1.        , -0.4284401 , -0.36612593],
       [ 0.87175378, -0.4284401 ,  1.        ,  0.96286543],
       [ 0.81794113, -0.36612593,  0.96286543,  1.        ]])

In [28]:
eig_vals_corr, eig_vectors_corr = np.linalg.eig(corr_matrix)

In [29]:
eig_vals_corr

array([2.91849782, 0.91403047, 0.14675688, 0.02071484])

In [30]:
eig_vectors_corr

array([[ 0.52106591, -0.37741762, -0.71956635,  0.26128628],
       [-0.26934744, -0.92329566,  0.24438178, -0.12350962],
       [ 0.5804131 , -0.02449161,  0.14212637, -0.80144925],
       [ 0.56485654, -0.06694199,  0.63427274,  0.52359713]])

###c) Singular Value Decomposition

In [31]:
u, s, v = np.linalg.svd(X_std.T)

In [32]:
u

array([[-0.52106591, -0.37741762,  0.71956635,  0.26128628],
       [ 0.26934744, -0.92329566, -0.24438178, -0.12350962],
       [-0.5804131 , -0.02449161, -0.14212637, -0.80144925],
       [-0.56485654, -0.06694199, -0.63427274,  0.52359713]])

In [33]:
s

array([20.92306556, 11.7091661 ,  4.69185798,  1.76273239])

In [34]:
v

array([[ 1.08239531e-01,  9.94577561e-02,  1.12996303e-01, ...,
        -7.27030413e-02, -6.56112167e-02, -4.59137323e-02],
       [-4.09957970e-02,  5.75731483e-02,  2.92000319e-02, ...,
        -2.29793601e-02, -8.63643414e-02,  2.07800179e-03],
       [ 2.72186462e-02,  5.00034005e-02, -9.42089147e-03, ...,
        -3.84023516e-02, -1.98939364e-01, -1.12588405e-01],
       ...,
       [ 5.43380310e-02,  5.12936114e-03,  2.75184277e-02, ...,
         9.89532683e-01, -1.41206665e-02, -8.30595907e-04],
       [ 1.96438400e-03,  8.48544595e-02,  1.78604309e-01, ...,
        -1.25488246e-02,  9.52049996e-01, -2.19201906e-02],
       [ 2.46978090e-03,  5.83496936e-03,  1.49419118e-01, ...,
        -7.17729676e-04, -2.32048811e-02,  9.77300244e-01]])

##2. Las Componentes Principales.

In [35]:
for ev in eig_vectors:
    print('La longitud del vector propio es:' , np.linalg.norm(ev))

La longitud del vector propio es: 0.9999999999999999
La longitud del vector propio es: 1.0000000000000002
La longitud del vector propio es: 0.9999999999999999
La longitud del vector propio es: 0.9999999999999999


In [36]:
eigen_pairs = [(np.abs(eig_vals[i]), eig_vectors[:, i]) for i in range(len(eig_vals))]
eigen_pairs

[(2.9380850501999953,
  array([ 0.52106591, -0.26934744,  0.5804131 ,  0.56485654])),
 (0.9201649041624852,
  array([-0.37741762, -0.92329566, -0.02449161, -0.06694199])),
 (0.14774182104494774,
  array([-0.71956635,  0.24438178,  0.14212637,  0.63427274])),
 (0.0208538621764632,
  array([ 0.26128628, -0.12350962, -0.80144925,  0.52359713]))]

In [37]:
eigen_pairs.sort()
eigen_pairs

[(0.0208538621764632,
  array([ 0.26128628, -0.12350962, -0.80144925,  0.52359713])),
 (0.14774182104494774,
  array([-0.71956635,  0.24438178,  0.14212637,  0.63427274])),
 (0.9201649041624852,
  array([-0.37741762, -0.92329566, -0.02449161, -0.06694199])),
 (2.9380850501999953,
  array([ 0.52106591, -0.26934744,  0.5804131 ,  0.56485654]))]

###Ordenamos los vectores propios con valores propios de mayor a menor.

In [38]:
eigen_pairs.reverse()
eigen_pairs

[(2.9380850501999953,
  array([ 0.52106591, -0.26934744,  0.5804131 ,  0.56485654])),
 (0.9201649041624852,
  array([-0.37741762, -0.92329566, -0.02449161, -0.06694199])),
 (0.14774182104494774,
  array([-0.71956635,  0.24438178,  0.14212637,  0.63427274])),
 (0.0208538621764632,
  array([ 0.26128628, -0.12350962, -0.80144925,  0.52359713]))]

In [39]:
print('Valores propios en orden descendente:')
print('')
for ep in eigen_pairs:
    print(ep[0])

Valores propios en orden descendente:

2.9380850501999953
0.9201649041624852
0.14774182104494774
0.0208538621764632


In [40]:
total_sum = sum(eig_vals)
total_sum

4.026845637583891

In [41]:
'''
La varianza explicativa nos dice cuanta información,
cuanta varianza explica cada una de las componentes.
'''
var_exp = [(i / total_sum) * 100 for i in sorted(eig_vals, reverse = True)]
var_exp

[72.9624454132999, 22.850761786701725, 3.66892188928287, 0.517870910715503]

In [42]:
cum_var_exp = np.cumsum(var_exp)
cum_var_exp

array([ 72.96244541,  95.8132072 ,  99.48212909, 100.        ])

In [43]:
!pip install bokeh
from bokeh.plotting import figure, show
from bokeh.io import output_notebook
output_notebook()

In [44]:
!pip install bokeh
from bokeh.plotting import figure, show, output_notebook
from bokeh.models import ColumnDataSource
import numpy as np

output_notebook()

# Datos ficticios para el ejemplo
var_exp = [40, 30, 20, 10]  # Porcentaje de varianza explicada por cada componente
cum_var_exp = np.cumsum(var_exp)  # Porcentaje acumulado

# Crear una ColumnDataSource para el gráfico de barras
source_bar = ColumnDataSource(data=dict(x=['CP %s' % i for i in range(1, 5)], y=var_exp))

# Crear una ColumnDataSource para el gráfico de dispersión y líneas
source_scatter = ColumnDataSource(data=dict(x=['CP %s' % i for i in range(1, 5)], y=cum_var_exp))

# Crear la figura principal
plot1 = figure(
    title="Porcentaje de variabilidad explicada por cada componente principal",
    x_axis_label="Componentes principales",
    y_axis_label="Porcentaje de varianza explicada",
    x_range=['CP %s' % i for i in range(1, 5)]
)

# Agregar barras verticales
plot1.vbar(x='x', top='y', width=0.5, source=source_bar, legend_label="Varianza Explicada")

# Agregar los puntos del gráfico de dispersión
plot1.circle(
    x='x', y='y', size=8, source=source_scatter, legend_label="Varianza Explicada Acumulada", color="red"
)

# Agregar líneas que conectan los puntos
plot1.line(
    x='x', y='y', source=source_scatter, legend_label="Línea Acumulada", color="red", line_width=2
)

# Personalizar la leyenda
plot1.legend.location = "top_right"  # Ubicar la leyenda
plot1.legend.click_policy = "hide"  # Permitir ocultar datos al hacer clic en la leyenda

# Mostrar el gráfico
show(plot1)


###Podemos seleccionar las dos primeras columnas, ya que ellas explican el 96% aproximadamente.

In [45]:
w = np.hstack((eigen_pairs[0][1].reshape(4, 1),
              eigen_pairs[1][1].reshape(4, 1)))
w

array([[ 0.52106591, -0.37741762],
       [-0.26934744, -0.92329566],
       [ 0.5804131 , -0.02449161],
       [ 0.56485654, -0.06694199]])

###Proyectando las variables del nuevo espacio vectorial

In [46]:
Y = X_std.dot(w)
Y

array([[-2.26470281, -0.4800266 ],
       [-2.08096115,  0.67413356],
       [-2.36422905,  0.34190802],
       [-2.29938422,  0.59739451],
       [-2.38984217, -0.64683538],
       [-2.07563095, -1.48917752],
       [-2.44402884, -0.0476442 ],
       [-2.23284716, -0.22314807],
       [-2.33464048,  1.11532768],
       [-2.18432817,  0.46901356],
       [-2.1663101 , -1.04369065],
       [-2.32613087, -0.13307834],
       [-2.2184509 ,  0.72867617],
       [-2.6331007 ,  0.96150673],
       [-2.1987406 , -1.86005711],
       [-2.26221453, -2.68628449],
       [-2.2075877 , -1.48360936],
       [-2.19034951, -0.48883832],
       [-1.898572  , -1.40501879],
       [-2.34336905, -1.12784938],
       [-1.914323  , -0.40885571],
       [-2.20701284, -0.92412143],
       [-2.7743447 , -0.45834367],
       [-1.81866953, -0.08555853],
       [-2.22716331, -0.13725446],
       [-1.95184633,  0.62561859],
       [-2.05115137, -0.24216355],
       [-2.16857717, -0.52714953],
       [-2.13956345,

In [47]:
from plotly.graph_objs import Line, Marker, Scene, Figure
import plotly.offline as py

results = []

for name in ('setosa', 'versicolor', 'virginica'):
    result = go.Scatter(x = Y[y == name, 0], y = Y[y == name, 1],
                        mode = 'markers', name = name,
                        marker = Marker(size = 12, line = Line(color = 'rgba(220, 220, 220, 0.15)', width = 0.5),
                        opacity = 0.8))
    results.append(result)

data = Data(results)
layout = Layout(showlegend = True,
                scene = Scene(xaxis = XAxis(title = 'Componente Principal 1', showline = False),
                              yaxis = YAxis(title = 'Componente Principal 2', showline = False)))

fig = Figure(data = data, layout = layout)
py.iplot(fig)

/usr/local/lib/python3.10/dist-packages/plotly/graph_objs/_deprecations.py:378: DeprecationWarning:

plotly.graph_objs.Line is deprecated.
Please replace it with one of the following more specific types
  - plotly.graph_objs.scatter.Line
  - plotly.graph_objs.layout.shape.Line
  - etc.


/usr/local/lib/python3.10/dist-packages/plotly/graph_objs/_deprecations.py:434: DeprecationWarning:

plotly.graph_objs.Marker is deprecated.
Please replace it with one of the following more specific types
  - plotly.graph_objs.scatter.Marker
  - plotly.graph_objs.histogram.selected.Marker
  - etc.


/usr/local/lib/python3.10/dist-packages/plotly/graph_objs/_deprecations.py:31: DeprecationWarning:

plotly.graph_objs.Data is deprecated.
Please replace it with a list or tuple of instances of the following types
  - plotly.graph_objs.Scatter
  - plotly.graph_objs.Bar
  - plotly.graph_objs.Area
  - plotly.graph_objs.Histogram
  - etc.


/usr/local/lib/python3.10/dist-packages/plotly/graph_objs/_deprecations